spring:
  application:
    name: msclientes

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 0 #Colocamos 0 para ele subir em uma porta randômica não ocupada

eureka:
  client:
    service-url:
      # Configura a aplicação para iniciar em uma porta aleatória não ocupada.
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    # Define o ID da instância no Eureka. Usa o nome da aplicação seguido de um valor aleatório gerado, garantindo um identificador único para cada instância da aplicação.
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}